title: My website
description: A website for me
url: https://shirsak.is-a.dev/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - coderay

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

kramdown:
  syntax-highlighter: coderay