title: Cherry Blossom
description: A theme for Jekyll inspired by Cactus Dark for Hexo.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed